[project]
site_name = "mathdocs"
site_description = "Notes on math"
site_author = "rastervc"
repo_url = "https://github.com/rastervc/mathdocs"
repo_name = "rastervc/mathdocs"
page_url = "rastervc.github.io/mathdocs"

nav = [
    { "Home" = "index.md" },
    { "Logic" = []},
    { "Abstract Algebra" = [
        "abstract-algebra/home.md",
        { "Group Theory" = [
            { "Inside a Group" = []},
            { "Group Actions" = []},
            { "Extensions of Groups" = [
                { "The Extension Toolkit" = [
                    { "Introduction" = "abstract-algebra/group-theory/extensions/toolkit/introduction.md" },
                    { "The Direct Product" = "abstract-algebra/group-theory/extensions/toolkit/direct-product.md" },
                    { "The Semidirect Product" = "abstract-algebra/group-theory/extensions/toolkit/semidirect-product.md" },
                    { "The Wreath Product" = "abstract-algebra/group-theory/extensions/toolkit/wreath-product.md" },
                    { "The Zappa-Sz√©p Product" = "abstract-algebra/group-theory/extensions/toolkit/zappa-szep-product.md" },
                ]},
                { "Abelian Groups" = []},
                { "Building With Abelian Groups" = [
                    { "Introduction" = "abstract-algebra/group-theory/extensions/building-with-abelian/introduction.md" },
                    { "Solvable Groups" = "abstract-algebra/group-theory/extensions/building-with-abelian/solvable-groups.md" },
                    { "Nilpotent Groups" = "abstract-algebra/group-theory/extensions/building-with-abelian/nilpotent-groups.md" },
                ]},
            ]},
            { "Groups and Primes" = [
                { "Various" = "abstract-algebra/group-theory/groups-and-primes/various.md" },
            ]},
            { "Representation Theory" = []},
            { "Geometric Group Theory" = []},
            { "Group Cohomology" = []},
        ]},
    ]},
    { "Analysis" = [
        "analysis/home.md",
        { "The Theory of Limits" = [
            { "Infinite Series" = [
                { "Uncountable Sums" = "analysis/theory-of-limits/infinite-series/uncountable-sums.md" },
            ]},
        ]},
        { "Real Analysis" = [
            { "Single Variable Integration" = [
                { "Primitives" = ""},
                { "The Riemann Integral" = [
                    "analysis/real-analysis/single-variable-integration/riemann-integral/introduction.md",
                    { "The Riemann-Stieltjes Integral" = "analysis/real-analysis/single-variable-integration/riemann-integral/riemann-stieltjes-integral.md"}
                ]},
                { "The Henstock-Kurzweil Integral" = "analysis/real-analysis/single-variable-integration/hk-integral.md" },
            ]}
        ]},
        { "Measure Theory" = []},
    ]},
    { "Geometry" = []},
    { "Number Theory" = []},
    { "Combinatorics" = []},
    { "Elementary Mathematics" = []},
    { "Competitive Programming" = []},
]

extra_javascript = [
    "javascripts/katex.js",
    "https://unpkg.com/katex@0/dist/katex.min.js",
    "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js",
]

extra_css = [
    "stylesheet/extra.css",
    "https://unpkg.com/katex@0/dist/katex.min.css",
]

[project.theme]
font.text = "Merriweather"
font.code = "JetBrains Mono"

features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.indexes",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.top",
    "navigation.tracking",
    "navigation.tabs",
    "search.highlight",
    # "toc.integrate"
]

[[project.theme.palette]] 
scheme = "default"
primary = "deep purple"
accent = "red"

[project.markdown_extensions.abbr]

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.attr_list]
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji" 
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.tables]
[project.markdown_extensions.md_in_html]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]

[project.markdown_extensions.toc]
permalink = true
title = "Contents"
toc_depth = 3