[project]
site_name = "mathdocs"
site_description = "Notes on math"
site_author = "rastervc"
repo_url = "https://github.com/rastervc/mathdocs"
repo_name = "rastervc/mathdocs"
page_url = "rastervc.github.io/mathdocs"

nav = [
    { "Home" = "index.md" },
    { "Abstract Algebra" = [
        { "Test" = "abstract-algebra/test.md" },
        { "Group Theory" = [
            { "Group Actions" = [
                { "Introduction" = "abstract-algebra/group-theory/group-actions/introduction.md" },
                { "Orbits and Stabiliziers" = "abstract-algebra/group-theory/group-actions/orbits-and-stabilizers.md" },
                { "Internal Group Actions" = [
                    { "By Translation, on Itself" = "abstract-algebra/group-theory/group-actions/internal-group-actions/translation-on-itself.md" },
                    { "By Translation, on Subsets" = "abstract-algebra/group-theory/group-actions/internal-group-actions/translation-on-subsets.md" },
                    { "By Conjugation, on Itself" = "abstract-algebra/group-theory/group-actions/internal-group-actions/conjugation-on-itself.md" },
                    { "By Conjugation, on Subsets" = "abstract-algebra/group-theory/group-actions/internal-group-actions/conjugation-on-subsets.md" },
                ]},
                { "Fixed Points" = "abstract-algebra/group-theory/group-actions/fixed-points.md" },
                { "Polya Counting" = "abstract-algebra/group-theory/group-actions/polya-counting.md" },
            ]},
        ]},
        { "Rings and Modules" = [
            { "Foundations" = "abstract-algebra/rings-and-modules/foundations.md" },
            { "Homomorphisms" = "abstract-algebra/rings-and-modules/homomorphisms.md" },
            { "Algebras" = "abstract-algebra/rings-and-modules/algebras.md" },
        ]},
    ]},
]

extra_javascript = [
    "javascripts/katex.js",
    "https://unpkg.com/katex@0/dist/katex.min.js",
    "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js",
]

extra_css = [
    "stylesheet/extra.css",
    "https://unpkg.com/katex@0/dist/katex.min.css",
]

[project.theme]
font.text = "Merriweather Sans"
font.code = "JetBrains Mono"

features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.indexes",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    # "toc.integrate"
]

[[project.theme.palette]] 
scheme = "default"
primary = "red"
accent = "deep purple"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
primary = "deep purple"
accent = "amber"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.markdown_extensions.abbr]

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.attr_list]
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji" 
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.tables]
[project.markdown_extensions.md_in_html]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]

[project.markdown_extensions.toc]
permalink = true
title = "Contents"